# Generated by Django 5.1.4 on 2025-02-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism_familiya', models.CharField(max_length=255)),
                ('tugilgan_sana', models.DateField()),
                ('sertifikat_rasmi', models.ImageField(upload_to='sertifikatlar/')),
                ('sertifikat_turi', models.CharField(max_length=100)),
            ],
        ),
    ]
